//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportLibrary {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesXMLExcel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesXMLExcel() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExportLibrary.ResourcesXMLExcel", typeof(ResourcesXMLExcel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/ss:Data&gt;&lt;/ss:Cell&gt;.
        /// </summary>
        internal static string CloseCell {
            get {
                return ResourceManager.GetString("CloseCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/ss:Row&gt;.
        /// </summary>
        internal static string CloseRow {
            get {
                return ResourceManager.GetString("CloseRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/ss:Table&gt;.
        /// </summary>
        internal static string CloseTable {
            get {
                return ResourceManager.GetString("CloseTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/ss:Worksheet&gt;.
        /// </summary>
        internal static string CloseWorkSheet {
            get {
                return ResourceManager.GetString("CloseWorkSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a False.
        /// </summary>
        internal static string FalseValue {
            get {
                return ResourceManager.GetString("FalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;/Workbook&gt;.
        /// </summary>
        internal static string FooterXML {
            get {
                return ResourceManager.GetString("FooterXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy.
        /// </summary>
        internal static string FormatDateTime {
            get {
                return ResourceManager.GetString("FormatDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;&lt;?mso-application progid=&quot;Excel.Sheet&quot;?&gt;&lt;Workbook xmlns=&quot;urn:schemas-microsoft-com:office:spreadsheet&quot;&gt;&lt;ss:Styles&gt;&lt;ss:Style ss:ID=&quot;1&quot;&gt;&lt;ss:Font ss:Bold=&quot;1&quot;/&gt;&lt;/ss:Style&gt;&lt;/ss:Styles&gt;.
        /// </summary>
        internal static string HeaderXML {
            get {
                return ResourceManager.GetString("HeaderXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ss:Cell&gt;&lt;ss:Data ss:Type=&quot;Number&quot;&gt;.
        /// </summary>
        internal static string OpenCellNumber {
            get {
                return ResourceManager.GetString("OpenCellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ss:Cell&gt;&lt;ss:Data ss:Type=&quot;String&quot;&gt;.
        /// </summary>
        internal static string OpenCellString {
            get {
                return ResourceManager.GetString("OpenCellString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ss:Row&gt;.
        /// </summary>
        internal static string OpenRow {
            get {
                return ResourceManager.GetString("OpenRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ss:Row ss:StyleID=&quot;1&quot;&gt;.
        /// </summary>
        internal static string OpenRowWithStyle {
            get {
                return ResourceManager.GetString("OpenRowWithStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ss:Table&gt;.
        /// </summary>
        internal static string OpenTable {
            get {
                return ResourceManager.GetString("OpenTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;ss:Worksheet ss:Name=&quot;Sheet 1&quot;&gt;.
        /// </summary>
        internal static string OpenWorkSheet {
            get {
                return ResourceManager.GetString("OpenWorkSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a True.
        /// </summary>
        internal static string TrueValue {
            get {
                return ResourceManager.GetString("TrueValue", resourceCulture);
            }
        }
    }
}
